var queue = new Queue();
queue.add(1);
queue.add(2);
queue.add(3);
console.log('====================================');
console.log(queue.print());
console.log('====================================');
queue.add(4);
console.log('====================================');
console.log(queue.get());
console.log('====================================');
console.log('====================================');
console.log(queue.print());
console.log('====================================');
