var hashTable = new HashTable(3);
hashTable.add('first', 1);
hashTable.add('second', 2);
hashTable.add('third', 3);
hashTable.add('fourth', 4);
hashTable.add('fifth', 5);
hashTable.print();
console.log('hash table length:', hashTable.length());
console.log('search second:', hashTable.search('second'));
hashTable.remove('fourth');
hashTable.remove('first');
hashTable.print();
console.log('hash table length:', hashTable.length());
